name: Run Stock Bot

on:
  schedule:
    # Changed '0' to '15' to avoid GitHub server delays
    # Runs at 9:15 AM, 10:15 AM... until 4:15 PM EST
    - cron: '11 14-21 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          DISCORD_URL: ${{ secrets.DISCORD_URL }}
        run: python stock_bot.py
